// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmSLBdr69CWAa-z5k7O-mu_ioM1aSYIv8',
    appId: '1:126183682637:web:edf94db34b23a53fbae204',
    messagingSenderId: '126183682637',
    projectId: 'poraoapp-46e47',
    authDomain: 'poraoapp-46e47.firebaseapp.com',
    storageBucket: 'poraoapp-46e47.appspot.com',
    measurementId: 'G-77G8BST8H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBI13JgSPFmX7m8G5SCo5SZr6qaqSGRU',
    appId: '1:126183682637:android:5b2a03d13bde9821bae204',
    messagingSenderId: '126183682637',
    projectId: 'poraoapp-46e47',
    storageBucket: 'poraoapp-46e47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7yumS_9lXVQ0e7uir3gfv19G5KE6_wx0',
    appId: '1:126183682637:ios:161de6ac1ff0bba6bae204',
    messagingSenderId: '126183682637',
    projectId: 'poraoapp-46e47',
    storageBucket: 'poraoapp-46e47.appspot.com',
    androidClientId: '126183682637-alkil2hgjljju99jskqripqnv8edmtmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.poraoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7yumS_9lXVQ0e7uir3gfv19G5KE6_wx0',
    appId: '1:126183682637:ios:d10436b3fd45e7c2bae204',
    messagingSenderId: '126183682637',
    projectId: 'poraoapp-46e47',
    storageBucket: 'poraoapp-46e47.appspot.com',
    androidClientId: '126183682637-alkil2hgjljju99jskqripqnv8edmtmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.poraoApp.RunnerTests',
  );
}
